version: '3.8'

services:
  codesentinel-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: codesentinel:dev
    container_name: codesentinel-dev
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=DEBUG
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - .:/app
      - dev_cache:/app/.cache
      - dev_mypy_cache:/app/.mypy_cache
    networks:
      - codesentinel-network
    command: ["tail", "-f", "/dev/null"]  # Keep container running for development

  codesentinel-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: codesentinel:dev
    container_name: codesentinel-test
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
      - test_reports:/app/test-reports
    networks:
      - codesentinel-network
    command: ["python", "-m", "pytest", "tests/", "-v", "--cov=src", "--cov-report=html:/app/test-reports/html", "--cov-report=xml:/app/test-reports/coverage.xml"]

volumes:
  dev_cache:
  dev_mypy_cache:
  test_reports:

networks:
  codesentinel-network:
    driver: bridge